#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinintely and prints "I am invincible!!!" when recieving a SIGTERM signal
while true
do
    echo "To infinity and beyond"
    trap 'echo "I am invincible!!!"' SIGTERM
    sleep 2
done