#!/usr/bin/env bash
# This script prints "bad luck" for the 4th loop, "good luck" for the 8th, else "Holberton School"
i=0
while [ $i -le 9 ]
do
    if [ $i == 3 ]
    then
        echo "bad luck"
    elif [ $i == 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi

    ((i++))
done