#!/usr/bin/env bash
#This script prints "bad luck from China" after 4, "bad luck from Japan" after 9, and "bad luck from Italy" after 17 using a while loop
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
        4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done